ServerSideConnect4/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ServerSideConnect4.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ServerSideConnect4/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerSideConnect4.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

ServerSideConnect4/Pages/Odot.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerSideConnect4.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ServerSideConnect4/Pages/Queries.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using ServerSideConnect4.Models;
using System.Collections;
using System.Numerics;
using static System.Net.Mime.MediaTypeNames;

namespace ServerSideConnect4.Pages
{
    public class QueriesModel : PageModel
    {
        private readonly ServerSideConnect4.Data.QContext _context;

        public QueriesModel(ServerSideConnect4.Data.QContext context)
        {
            _context = context;
            this.countries = new List<SelectListItem>
            {
                new SelectListItem { Value = "Israel", Text = "Israel" },
                new SelectListItem { Value = "Mexico", Text = "Mexico" },
                new SelectListItem { Value = "Canada", Text = "Canada" },
                new SelectListItem { Value = "United Kingdom", Text = "United Kingdom" },
                new SelectListItem { Value = "Germany", Text = "Germany" },
                new SelectListItem { Value = "France", Text = "France" },
                new SelectListItem { Value = "Italy", Text = "Italy" },
                new SelectListItem { Value = "Spain", Text = "Spain" },
                new SelectListItem { Value = "Japan", Text = "Japan" },
                new SelectListItem { Value = "China", Text = "China" },
                new SelectListItem { Value = "Australia", Text = "Australia" },
                new SelectListItem { Value = "South Korea", Text = "South Korea" },
                new SelectListItem { Value = "Brazil", Text = "Brazil" },
                new SelectListItem { Value = "Argentina", Text = "Argentina" },
                new SelectListItem { Value = "India", Text = "India" },
                new SelectListItem { Value = "Russia", Text = "Russia" },
                new SelectListItem { Value = "South Africa", Text = "South Africa" },
                new SelectListItem { Value = "Nigeria", Text = "Nigeria" },
                new SelectListItem { Value = "Egypt", Text = "Egypt" },
                new SelectListItem { Value = "USA", Text = "USA" }

            };
        }

        public IList<Player> Player { get; set; } = default!;
        public IList<GameData> LastGamesDate { get; set; } = default!;
        public IList<GameData> AllGames { get; set; } = default!;
        public List<SelectListItem> players { get; set; }
        [BindProperty]
        public int selectPlayers { get; set; }
        [BindProperty]
        public string selectCountry { get; set; }
        public IList<GameData> AllSelectedPlayerGames { get; set; } = default!;
        public IList<Player> AllSelectedPlayerCountry { get; set; } = default!;
        public List<SelectListItem> countries { get; set; }
        public List<PlayerGamesCountViewModel> PlayerGamesCount { get; set; }
        public List<PlayersByAmountOfGames> playersByAmountOfGames { get; set; } = default!;

        public async Task OnGetAsync()
        {
            if (_context.Player != null)
            {
                await GetPlayers();
            }
            if (_context.GameDatas != null)
            {
                await OnGetLastGameDateAsync();
                AllGames = await _context.GameDatas.ToListAsync(); //Q19
                await OnGetPlayersCountAsync();
                await OnGetPlayersByAmountOfGamesAsync();
            }
        }

        public async Task OnGetWithoutPlayerAsync()
        {
            if (_context.GameDatas != null)
            {
                await OnGetLastGameDateAsync();
                AllGames = await _context.GameDatas.ToListAsync();
                await GetPlayers();
                await OnGetPlayersCountAsync();
                await OnGetPlayersByAmountOfGamesAsync();

            }
        }

        //Q17
        public async Task OnGetSortAsync(string sortOrder)
        {
            IQueryable<Player> playersQuery = _context.Player.AsQueryable();

            // Handle sorting
            if (!string.IsNullOrEmpty(sortOrder))
            {
                switch (sortOrder)
                {
                    case "id_asc":
                        playersQuery = playersQuery.OrderBy(p => p.ID);
                        break;
                    case "id_desc":
                        playersQuery = playersQuery.OrderByDescending(p => p.ID);
                        break;
                    // Add more cases for other columns, if needed
                    default:
                        playersQuery = playersQuery.OrderBy(p => p.ID);
                        break;
                }
                await OnGetWithoutPlayerAsync();
            }
            else
            {
                // Default sorting by ID in ascending order
                playersQuery = playersQuery.OrderBy(p => p.ID);
            }

            Player = await playersQuery.ToListAsync();
        }
        //Q17
        public async Task<IActionResult> OnPostSortOrderAsync(string sortOrder)
        {
            await OnGetSortAsync(sortOrder);
            return Page();
        }

        //Q18
        public async Task OnGetLastGameDateAsync()
        {
            var lastGamesData = await _context.GameDatas
                .ToListAsync();

            LastGamesDate = lastGamesData
                .GroupBy(g => g.PlayerName) // Group by PlayerName
                .Select(g => new GameData
                {
                    PlayerName = g.Key,
                    BeginningGameDate = g.Max(x => x.BeginningGameDate)
                })
                .OrderBy(g => g.PlayerName, new LowercaseThenUppercaseComparer())
                .ToList();
        }

        //Q21
        public async Task<IActionResult> OnPostSelectedPlayerAsync()
        {
            await OnGetSelectedPlayerAsync();
            return Page();
        }
        //Q21
        public async Task OnGetSelectedPlayerAsync()
        {
            var filteredGames = _context.GameDatas.Where(game =>
                game.PlayerID == selectPlayers)
                .ToList();
            AllSelectedPlayerGames = filteredGames;
            await OnGetAsync();
        }
        //Q22
        public async Task OnGetPlayersCountAsync()
        {
            var playerGamesCount = _context.GameDatas
                .GroupBy(game => game.PlayerName)
                .Select(group => new PlayerGamesCountViewModel { PlayerName = group.Key, GamesPlayed = group.Count() })
                .ToList();
            PlayerGamesCount = playerGamesCount;
        }
        public List<GameData> GetGamesPlayedByPlayerID(string playerName)
        {
            var filteredGames = _context.GameDatas.Where(game =>
                game.PlayerID.Equals(playerName))
                .ToList();
            return filteredGames;
        }

        //Q24
        public async Task<IActionResult> OnPostSelectedCountryAsync()
        {
            await OnGetSelectedCountryAsync();
            return Page();
        }

        //Q24
        public async Task OnGetSelectedCountryAsync()
        {
            var filteredPlayersPerCountry = _context.Player.Where(player =>
                player.Country.Equals(selectCountry))
                .ToList();
            AllSelectedPlayerCountry = filteredPlayersPerCountry;
            await OnGetAsync();
        }

        private async Task GetPlayers()
        {
            Player = await _context.Player.ToListAsync();
            players = new List<SelectListItem> { };
            for (int i = 0; i < Player.Count; i++)
            {
                this.players.Add(new SelectListItem(Player[i].FirstName, Player[i].ID + ""));
            }
        }

        //Q23
        public async Task OnGetPlayersByAmountOfGamesAsync()
        {
            var playersGroups = await _context.GameDatas
            .GroupBy(g => g.PlayerID)
            .Select(g => new PlayersByAmountOfGames
            {
                GamesPlayed = g.Count(),
                Players = _context.Player.Where(p => g.Any(gd => gd.PlayerID == p.ID)).ToList()
            })
            .ToListAsync();
            playersByAmountOfGames = playersGroups;


            var playersWithoutGameData = Player.GroupJoin(AllGames, player => player.ID, gameData => gameData.PlayerID,
                (player, gameDataGroup) => new { Player = player, GameDataGroup = gameDataGroup })
                    .Where(x => !x.GameDataGroup.Any())
                    .Select(x => x.Player).ToList();

            PlayersByAmountOfGames playerDidntPlay = new PlayersByAmountOfGames { GamesPlayed = 0 };
            playerDidntPlay.Players = playersWithoutGameData;

            playersByAmountOfGames.Add(playerDidntPlay);

        }
    }
}

public class LowercaseThenUppercaseComparer : IComparer<string>
{
    public int Compare(string x, string y)
    {
        bool xIsLowercase = char.IsLower(x[0]);
        bool yIsLowercase = char.IsLower(y[0]);

        if (xIsLowercase && !yIsLowercase)
            return -1;
        if (!xIsLowercase && yIsLowercase)
            return 1;

        return string.Compare(x, y, StringComparison.Ordinal);
    }
}

public class PlayerGamesCountViewModel
{
    public string PlayerName { get; set; }
    public int GamesPlayed { get; set; }
}

public class PlayersByAmountOfGames
{
    public int GamesPlayed { get; set; }
    public List<Player> Players { get; set; } = default!;
}

ServerSideConnect4/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>This is a site that host all of the queries and registration for our "Connect 4" project.</p>
</div>

ServerSideConnect4/Pages/Odot.cshtml
@page
@model PrivacyModel
@{
    ViewData["Title"] = "About us";
}
<h1>@ViewData["Title"]</h1>

<p>Itay Mortov, 316334697</p>

<p>Omri Gispan, 318324613</p>

ServerSideConnect4/Pages/Queries.cshtml
@page
@model ServerSideConnect4.Pages.QueriesModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h4 class="display-10">Showing all the players with all the details, with the option to sort by name without sensitive case</h4>
</div>

<p class="d-inline-flex">

    <form method="post" asp-page-handler="SortOrder">
        <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="true" aria-controls="collapseExample">
            Show players details
        </a>
        <button class="btn btn-primary" type="submit" name="SortOrder" value="id_asc">Sort by ID Ascending</button>
        <button class="btn btn-primary" type="submit" name="SortOrder" value="id_desc">Sort by ID Descending</button>
    </form>


</p>
<div class="collapse show" id="collapseExample">
    <div class="card card-body">
        @if (Model?.Player != null)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Player[0].ID)
                        </th>
                        <th>
                            First Name
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Player[0].Phone)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Player[0].Country)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Player)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Phone)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Country)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            }
            </div>
</div>

<hr class="hr" />
<div class="text-center">
    <h4 class="display-10">All player's names with their date of last game </h4>
</div>

<p class="d-inline-flex gap-1 mt-3">
    <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#contentCollapse" aria-expanded="false" aria-controls="contentCollapse">
        Show table
    </button>
</p>

<div class="collapse show" id="contentCollapse">
    <div class="card card-body">
        @if (Model?.LastGamesDate != null)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>Player First Name</th>
                        <th>Last Game Date</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.LastGamesDate)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.PlayerName)</td>
                            <td>@Html.DisplayFor(modelItem => item.BeginningGameDate)</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</div>

<hr class="hr" />
<div class="text-center">
    <h4 class="display-10">All games details</h4>
</div>

<div class="collapse show" id="collapseGames">
    <div class="card card-body">
        @if (Model?.AllGames != null)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>Game ID</th>
                        <th>Player ID</th>
                        <th>Player first name</th>
                        <th>Date of game</th>
                        <th>Game duration</th>
                        <th>Winner</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.AllGames)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PlayerID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PlayerName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.BeginningGameDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TimeDurationGame)
                            </td>
                            @if (item.isPlayerWin)
                            {
                                <td>Player</td>
                            } else {
                            <td>Computer</td>
                            }

                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</div>

<hr class="hr" />
<div class="text-center">
    <h4 class="display-10"> Select a player to show all the games </h4>
</div>

<form method="post" asp-page-handler="SelectedPlayer">
    @Html.AntiForgeryToken()
    <select id="playersCombo" class="form-select" asp-items="@Model.players" asp-for="@Model.selectPlayers" onchange="this.form.submit();">
        <option selected disabled value="">Choose...</option>
    </select>
</form>

<div class="card card-body">
    @if (Model?.AllSelectedPlayerGames != null)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Game ID</th>
                    <th>Player ID</th>
                    <th>Player first name</th>
                    <th>Date of game</th>
                    <th>Game duration</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.AllSelectedPlayerGames)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PlayerID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PlayerName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BeginningGameDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TimeDurationGame)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>


@if (!string.IsNullOrEmpty(Request.Query["playerName"]))
{
    var playerName = Request.Query["playerName"];
    var playerGames = Model.GetGamesPlayedByPlayerID(playerName + "");

    if (playerGames.Any())
    {
        <h3>Games played by @playerName:</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Player Name</th>
                    <th>Player ID</th>
                    <th>Time Duration</th>
                    <th>Beginning Game Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var game in playerGames)
                {
                    <tr>
                        <td>@game.PlayerName</td>
                        <td>@game.PlayerID</td>
                        <td>@game.TimeDurationGame</td>
                        <td>@game.BeginningGameDate</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No games found for @playerName.</p>
    }
}

<hr class="hr" />
<div class="text-center">
    <h4 class="display-10">All player's names with their count of played games </h4>
</div>

<div class="card card-body">
    @if (Model?.PlayerGamesCount != null)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Player first name</th>
                    <th>Amount of games</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.PlayerGamesCount)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.PlayerName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.GamesPlayed)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>


<hr class="hr" />
<div class="text-center">
    <h4 class="display-10">Select country to show all players that attach </h4>
</div>

<form method="post" asp-page-handler="SelectedCountry">
    @Html.AntiForgeryToken()
    <select id="playersCombo" class="form-select" asp-items="@Model.countries" asp-for="@Model.selectCountry" onchange="this.form.submit();">
        <option selected disabled value="">Choose...</option>
    </select>
</form>

<div class="card card-body">
    @if (Model?.AllSelectedPlayerCountry != null)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Player[0].ID)
                    </th>
                    <th>
                        First Name
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Player[0].Phone)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Player[0].Country)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.AllSelectedPlayerCountry)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FirstName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Phone)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Country)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>


<hr class="hr" />
<div class="text-center">
    <h4 class="display-10"> All players groups into amount of played </h4>
</div>

@foreach (var playersTable in Model.playersByAmountOfGames)
{
    <h4>Players who played @playersTable.GamesPlayed times:</h4>
    <div class="card">
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>First Name</th>
                        <th>Phone</th>
                        <th>Country</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var player in playersTable.Players)
                    {
                        <tr>
                            <td>@player.ID</td>
                            <td>@player.FirstName</td>
                            <td>@player.Phone</td>
                            <td>@player.Country</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}